# Generated by Django 2.1.3 on 2018-11-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20181107_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='desc',
            field=models.TextField(default='no desc', max_length=500, verbose_name='Описание '),
        ),
    ]
