# Generated by Django 2.1.3 on 2018-12-09 18:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
                ('conent', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='Комлектующие в категории')),
            ],
        ),
    ]
