# Generated by Django 2.1.3 on 2018-12-09 18:30

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_sourcedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedetail',
            name='conent',
        ),
        migrations.AddField(
            model_name='sourcedetail',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
