# Generated by Django 2.1.3 on 2018-12-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_auto_20181209_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedetail',
            name='short_desc',
            field=models.CharField(default='Краткое описание', max_length=255, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='sourcedetail',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Назва'),
        ),
    ]
